spring.application.name=webhook-delivery-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/webhook_delivery_platform
spring.datasource.username=webhook_app
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate